name: Continuous Integration

on: [push, pull_request]

jobs:
  Linux:
    name: Linux | ${{ matrix.build-system.name }} | ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-system:
          - name: "Cmake"
            dependency: cmake
            config-command-dev: cmake -DCMAKE_BUILD_TYPE=Release -DDEV_ENV=ON -S . -B build
            config-command-rel: cmake -DCMAKE_BUILD_TYPE=Release -DDEV_ENV=OFF -S . -B build
            build-command: cmake --build build --parallel 2
          - name: "Autotools"
            dependency: automake
            config-command-dev: ./autogen.sh
            config-command-rel: ./autogen.sh
            build-command: make -j 2
        env: [DEV_ENV, REL_ENV]
        exclude:
          - build-system:
              name: "Autotools"
            env: DEV_ENV
    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get install gcc make libsdl2-dev libsdl2-net-dev libsdl2-mixer-dev libpng-dev libsamplerate-dev ${{ matrix.build-system.dependency }}

      - uses: actions/checkout@v2

      - name: Configure
        shell: bash
        run: |
          if [[ "${{ matrix.env }}" == 'DEV_ENV' ]]; then
            ${{ matrix.build-system.config-command-dev }}
          else
            ${{ matrix.build-system.config-command-rel }}
          fi

      - name: Build
        shell: bash
        run: |
          export MAKEFLAGS=--keep-going
          ${{ matrix.build-system.build-command }}
