name: Continuous Integration

on:
  push:
    branches: ["*"]
    paths-ignore: ["src_dos/**"]
    tags-ignore: ["*"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Cmake:
    name: ${{ matrix.os.name }} | ${{ matrix.arch.name }} | ${{ matrix.compiler.display_name }}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          -
            name: "Windows"
            runner: "windows-2019" # windows-2022
          -
            name: "Linux"
            runner: "ubuntu-22.04"
        arch:
          -
            name: "x86"
            bits: "32"
            msys_name: "i686"
            msvc_gen_opts: "-T v141_xp -A Win32"
            msvc_triplet: "x86-windows"
          -
            name: "x64"
            bits: "64"
            msys_name: "x86_64"
            msvc_gen_opts: "-A x64"
            msvc_triplet: "x64-windows"
        compiler:
          -
            display_name: "GCC"
            name: "gcc"
            msys_msystem_prefix: "MINGW"
            msys_package_prefix: "mingw-w64"
            cmake_gen: "Ninja"
          -
            display_name: "GCC-Ucrt"
            name: "gcc"
            msys_msystem_prefix: "UCRT"
            msys_package_prefix: "mingw-w64-ucrt"
            cmake_gen: "Ninja"
          -
            display_name: "Clang"
            name: "clang"
            msys_msystem_prefix: "CLANG"
            msys_package_prefix: "mingw-w64-clang"
            cmake_gen: "Ninja"
          -
            display_name: "MSVC"
            name: "cl"
            cmake_gen: "Visual Studio 16 2019" # Visual Studio 17 2022
            vcpkg-version: 'latest'
        exclude:
          - # Disable x86 build on linux (require crosscompiling)
            os:
              name: "Linux"
            arch:
              name: "x86"
          - # Disable MSVC compiler on Linux (no MSVC for Linux)
            os:
              name: "Linux"
            compiler:
              display_name: "MSVC"
          - # Disable GCC-Ucrt compiler on Linux (no MSYS UCRT for Linux)
            os:
              name: "Linux"
            compiler:
              display_name: "GCC-Ucrt"
          - # Disable GCC-Ucrt compiler for x86 (no MSYS UCRT32 env)
            os:
              name: "Windows"
            compiler:
              display_name: "GCC-Ucrt"
            arch:
              name: "x86"
          - # Disable MSVC compiler for x86
            compiler:
              display_name: "MSVC"
            arch:
              name: "x86"
        include:
          -
            shell: "bash"
          -
            os:
              name: "Windows"
            compiler:
              display_name: "GCC"
            shell: "msys2 {0}"
          -
            os:
              name: "Windows"
            compiler:
              display_name: "GCC-Ucrt"
            shell: "msys2 {0}"
          -
            os:
              name: "Windows"
            compiler:
              display_name: "Clang"
            shell: "msys2 {0}"
          - # Add special config "GCC-Ucrt x86" using MSYS MINGW32 env and ucrt hack
            os:
              name: "Windows"
              runner: "windows-2019" # windows-2022
            arch:
              name: "x86"
              bits: "32"
              msys_name: "i686"
            compiler:
              display_name: "GCC-Ucrt"
              name: "gcc"
              msys_msystem_prefix: "MINGW"
              msys_package_prefix: "mingw-w64"
              cmake_gen: "Ninja"
            shell: "msys2 {0}"
            cmake_opts: "-D ID_X_UCRT32=ON"
    defaults:
      run:
        shell: ${{ matrix.shell }}
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup env, Build and Test
        uses: ./.github/actions/id_build
        timeout-minutes: 15
        with:
          shell: ${{ matrix.shell }}
          cmake-generator: ${{ matrix.compiler.cmake_gen }}
          cmake-extra-options: ${{ matrix.compiler.msvc_gen_opts }}
          compiler: ${{ matrix.compiler.name }}
          msys-msystem: ${{ matrix.compiler.msys_msystem_prefix != '' && format('{0}{1}', matrix.compiler.msys_msystem_prefix, matrix.arch.bits) || '' }}
          vcpkg-version: ${{ matrix.compiler.vcpkg-version }}
          portable: true

      - name: Test Windows
        if: ${{ matrix.os.name == 'Windows' }}
        run: |
          cd build
          ctest --output-on-failure -C RelWithDebInfo

      - name: Test Linux
        if: ${{ matrix.os.name == 'Linux' }}
        env:
          SDL_VIDEODRIVER: dummy
        run: |
          cd build
          ctest --output-on-failure

      - name: Install
        if: |
          github.repository == 'JNechaevsky/inter-doom' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master' &&
          matrix.os.name == 'Windows'
        run: |
          cmake --install build --config RelWithDebInfo --prefix "./build/install"

      - name: Package Zip
        if: |
          github.repository == 'JNechaevsky/inter-doom' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master' &&
          matrix.os.name == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: inter-doom-${{ steps.configure.outputs.rev_number }}-${{ steps.configure.outputs.sha_short }}-windows-${{ matrix.arch.name }}-${{ matrix.compiler.display_name }}
          path: ./build/install/
