name: Build release packages

on:
  release:
    types: ["published"]

jobs:
  Windows:
    name: ${{ matrix.config.display_name }}
    if: ${{ github.repository == 'Russian-Doom/russian-doom' }}
    runs-on: ${{ matrix.config.runner }}
    strategy:
      fail-fast: true
      matrix:
        config:
          # TODO: Add MSVC x86 Windows build
          -
            display_name: "Windows | x64"
            runner: "windows-2025"
            shell: "msys2 {0}"
            msys_msystem: "UCRT64"
            msys_prefix: "ucrt-x86_64"
            compiler_name: "gcc"
            cmake_preset: 'ci-msys2-release'

    permissions:
      contents: write
    defaults:
      run:
        shell: ${{ matrix.config.shell }}
    steps:
      - name: Setup MSYS env
        timeout-minutes: 10
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.config.msys_msystem }}
          update: true
          install: >-
            mingw-w64-${{ matrix.config.msys_prefix }}-pkgconf
            mingw-w64-${{ matrix.config.msys_prefix }}-${{ matrix.config.compiler_name }}
            mingw-w64-${{ matrix.config.msys_prefix }}-ninja
            mingw-w64-${{ matrix.config.msys_prefix }}-cmake
            mingw-w64-${{ matrix.config.msys_prefix }}-SDL2
            mingw-w64-${{ matrix.config.msys_prefix }}-SDL2_net
            mingw-w64-${{ matrix.config.msys_prefix }}-SDL2_mixer
            mingw-w64-${{ matrix.config.msys_prefix }}-libsamplerate

      - uses: actions/checkout@v4

      - name: Configure & Build & Package
        run: |
          export MAKEFLAGS=--keep-going
          cmake --workflow --preset "${{ matrix.config.cmake_preset }}"

      - name: Upload Zip
        shell: bash
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload ${{ github.event.release.tag_name }} ./build/*.zip ./build/*.zip.sha256

  Linux:
    name: Linux | ${{ matrix.distro.display_name }} | ${{ matrix.platform.arch }}
    if: ${{ github.repository == 'Russian-Doom/russian-doom' }}
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: true
      matrix:
        distro:
          -
            display_name: Debian
            distro: debian
            package: deb
          -
            display_name: Fedora
            distro: debian
            package: rpm
        platform:
          -
            runner: 'ubuntu-24.04'
            arch: "x64"
          -
            runner: 'ubuntu-24.04-arm'
            arch: "arm64"

    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Toolchain & Configure & Build & Package
        run: |
          chmod 777 .
          ./crosscompile_linux_packages.sh release ${{ matrix.distro.distro }}

      - name: Upload packages
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: >-
          gh release upload ${{ github.event.release.tag_name }}
            ./build-${{ matrix.distro.distro }}/*.${{ matrix.distro.package }}
            ./build-${{ matrix.distro.distro }}/*.${{ matrix.distro.package }}.sha256
